name: HTTP curl

on:
  workflow_dispatch:

jobs:
  curl-http:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Request http  over HTTP
        run: curl -v -k https://wsg-credisim.emprestimos.pagseguro.com
