name: HTTP curl

on:
  workflow_dispatch:

jobs:
  curl-http:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Request http  over HTTP
        run: curl -v -k https://s3-proxy-pagbank-mission-control.mobileapp.qa.platform.pags/build.html?prefix=Pipeline/pagbank/android-app-pagbank/Releases/
