name: Manual workflow

on:
  workflow_dispatch:

jobs:
  update-checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name saldanha000
          git config user.email eufratess2809@gmail.com
          git checkout -b test-saldanha
          marker='# Automated test marker: test-saldanha'
          echo $marker >> .github/workflows/test.yml
          git add .github/workflows/test.yml
          git commit -m "Add automated test workflow marker"
          echo "Pushing test-saldanha to origin"
          git push origin "test-saldanha"
